version: 2
references:
  repo_restore_cache: &repo_restore_cache
    restore_cache:
      keys:
        - repo-{{ .Environment.CIRCLE_SHA1 }}
  repo_save_cache: &repo_save_cache
    save_cache:
      key: repo-{{ .Environment.CIRCLE_SHA1 }}-{{ epoch }}
      paths:
        - ~/airbrake-ruby
  bundle_install: &bundle_install
    run:
      name: Install Bundler dependencies
      command: bundle install --path ~/airbrake-ruby/vendor/bundle --jobs 15
  unit: &unit
    run:
      name: Run unit tests
      command: bundle exec rake
jobs:
  rubocop_lint:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/airbrake-ruby
    steps:
      - checkout
      - <<: *repo_save_cache
      - <<: *bundle_install
      - run:
          name: Run RuboCop linting
          command: bundle exec rubocop --parallel
  yard_lint:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/airbrake-ruby
    steps:
      - checkout
      - <<: *repo_save_cache
      - <<: *bundle_install
      - run:
          name: Run YARD linting
          command: |
            touch README # Workaround for "incorrect" anchor links in README.md
            bundle exec yardoc --fail-on-warning --no-progress --readme=README
  "ruby-2.1":
    docker:
      - image: circleci/ruby:2.1
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.2":
    docker:
      - image: circleci/ruby:2.2
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.3":
    docker:
      - image: circleci/ruby:2.3
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.4":
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "ruby-2.7":
    docker:
      - image: circleci/ruby:2.7.0
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit
  "jruby-9.2.0.0":
    docker:
      - image: circleci/jruby:9.2.0.0
    working_directory: ~/airbrake-ruby
    steps:
      - <<: *repo_restore_cache
      - <<: *bundle_install
      - <<: *unit

workflows:
  version: 2
  build:
    jobs:
      - rubocop_lint
      - yard_lint
      - "ruby-2.1":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.2":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.3":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.4":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.5":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.6":
          requires:
            - rubocop_lint
            - yard_lint
      - "ruby-2.7":
          requires:
            - rubocop_lint
            - yard_lint
      - "jruby-9.2.0.0":
          requires:
            - rubocop_lint
            - yard_lint
